### PR TITLE
Add sqlite boilerplate

### PR DESCRIPTION
**Pull request by natanlao**
Would appreciate pointers on how to better structure this

### CODE REVIEW

**Review by penguingovernor — CHANGES_REQUESTED** [review]
This code looks good to me, let's just make it into its own package so we have some nice modularity between the parts

**Comment by natanlao** [comment]
Is this just moving it into its own folder?

**Comment by penguingovernor** [comment]
> Is this just moving it into its own folder?

Yeah we'd have to give it a package name too as well. Since we're going to be sharing this repo with the hardware team it might be wise to make some folders named `server`, `sensor`, and `client` in the root of this repo.

So we'd have this file in `server/somePkgName` , which brings up the fact that we'll have to use go modules for this so I can init that and start it.

**Review by penguingovernor — APPROVED** [review]
lgtm (:

**Review by LexiKat — APPROVED** [review]
This looks good. Thanks Natan

**Pull request merged**
