### PR TITLE
Add: grpc bindings for python

### PR DESCRIPTION
**Pull request by penguingovernor**
GRPC python bindings should be ready to go!

### CODE REVIEW

**Comment by penguingovernor** [comment]
Should help out with #12

**Review by natanlao — APPROVED** [review]
Not much to review since they are generated automatically. How do you generate these? If these files can be generated from the command line, I am inclined to not commit them and generate them on the fly.

**Comment by penguingovernor** [comment]
> Not much to review since they are generated automatically. How do you generate these? If these files can be generated from the command line, I am inclined to not commit them and generate them on the fly.

It's the protoc compiler and each language needs support libraries, I'd be open to remove these generated files once we get a build system in place, especially once we have to start modifying the datagram.proto file.

**Comment by natanlao** [comment]
Okay, I'm happy to kick the metaphorical can down the metaphorical road on this one in that case :+1:

**Review by RocktheKage — APPROVED** [review]

**Pull request merged**
