### PR TITLE
Rudimentary client

### LINKED ISSUE #22: Client shell
Client that can
- Pull database from server
- Load database with sql.js
- Dump data in the database into page

### PR DESCRIPTION
**Pull request by natanlao**
Closes #22 
Jennie and I wrote a basic client page that pulls the database, loads it into the browser, and displays its contents in a table. Here's what it looks like with dummy data:

image

### CODE REVIEW

**Review by penguingovernor — CHANGES_REQUESTED** [review]
Everything looks good to me, we're missing one column for the (request ID/bus ID) but other than that great work y'all :)

**Comment by natanlao** [comment]
The columns are populated automatically based on the table schema, so when it's merged, it will pull the new column names

**Comment by penguingovernor** [comment]
> The columns are populated automatically based on the table schema, so when it's merged, it will pull the new column names

Amazing! Approving now, great job again y'all

**Review by penguingovernor — APPROVED** [review]
Good to go!

**Review by jennie-n — APPROVED** [review]

**Pull request merged**
